knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    image:
        enabled:    true
        binary:     "\"C:\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:    []